# Generated by Django 3.2.7 on 2021-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210906_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='winner',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
